import React, { useState, useEffect } from 'react';
import { 
  Users, 
  Trash2, 
  ShieldCheck, 
  Smartphone, 
  Mail, 
  CheckCircle2, 
  AlertTriangle, 
  RefreshCw, 
  ArrowRight, 
  Check, 
  Sparkles,
  Info,
  ShieldAlert,
  KeyRound,
  Lock,
  Database,
  Eye,
  EyeOff,
  Shield,
  X
} from 'lucide-react';
import { UserAuthSession } from '../types';
import { 
  sendCitizenPhoneOtp, 
  verifyCitizenPhoneOtp, 
  sendEcoCitizenAiOtp,
  verifyEcoCitizenAiOtp,
  authenticateAdministrator
} from '../utils/authSessionManager';
import { OFFICIAL_ADMIN_EMAIL, recordSecurityAccessLog } from '../utils/adminStore';
import { OnlineUpdateModal } from './OnlineUpdateModal';

interface AuthPortalProps {
  onAuthenticated: (session: UserAuthSession) => void;
}

export function AuthPortal({ onAuthenticated }: AuthPortalProps) {
  const [showUpdateModal, setShowUpdateModal] = useState(false);

  // Hidden AI Studio administrator access (strictly reserved for AI Studio via URL parameter ?admin=ai_studio)
  const isAiStudioAdmin = typeof window !== 'undefined' && (
    new URLSearchParams(window.location.search).get('admin') === 'ai_studio' ||
    new URLSearchParams(window.location.search).get('admin') === 'true'
  );

  // =========================================================================
  // 1. ESPACE CITOYEN (ACCUEIL PRINCIPAL - LARGEMENT VISIBLE & ACCESSIBLE)
  // =========================================================================
  const [citizenNom, setCitizenNom] = useState('');
  const [citizenPhone, setCitizenPhone] = useState('+243 ');
  const [citizenAddress, setCitizenAddress] = useState('');
  const [citizenCommune, setCitizenCommune] = useState('Gombe');
  const [citizenOtpSent, setCitizenOtpSent] = useState(false);
  const [autoGeneratedCode, setAutoGeneratedCode] = useState('');
  const [enteredOtp, setEnteredOtp] = useState('');
  const [citizenLoading, setCitizenLoading] = useState(false);
  const [citizenError, setCitizenError] = useState('');
  const [citizenSuccessMsg, setCitizenSuccessMsg] = useState('');

  // Communes de Kinshasa pour simplifier la sélection citoyenne
  const KINSHASA_COMMUNES = [
    'Gombe', 'Bandalungwa', 'Barumbu', 'Bumbu', 'Kalamu', 'Kasa-Vubu', 
    'Kimbanseke', 'Kisenso', 'Lemba', 'Limete', 'Lingwala', 'Makala', 
    'Maluku', 'Masina', 'Matete', 'Mont-Ngafula', 'Ndjili', 'Ngaba', 
    'Ngaliema', 'Ngiri-Ngiri', 'Nsele', 'Ouenze', 'Selembao'
  ];

  // Génération du code OTP par l'IA pour l'espace éco-citoyen seulement
  const handleGenerateCitizenCode = async (e: React.FormEvent) => {
    e.preventDefault();
    setCitizenError('');
    setCitizenSuccessMsg('');

    if (!citizenNom.trim()) {
      setCitizenError('Veuillez renseigner votre nom ou prénom complet.');
      return;
    }

    const cleanNumber = citizenPhone.replace(/\s+/g, '');
    if (!cleanNumber || cleanNumber.length < 8) {
      setCitizenError('Veuillez renseigner un numéro de téléphone mobile valide (+243...)');
      return;
    }

    if (!citizenAddress.trim()) {
      setCitizenError('Veuillez renseigner votre adresse précise (Avenue, Numéro, Quartier).');
      return;
    }

    setCitizenLoading(true);
    try {
      const res = await sendEcoCitizenAiOtp(
        citizenNom.trim(),
        cleanNumber,
        citizenAddress.trim(),
        citizenCommune
      );

      if (res.success) {
        setAutoGeneratedCode(res.code);
        setEnteredOtp(res.code); // Pré-remplissage intelligent
        setCitizenOtpSent(true);
        setCitizenSuccessMsg(`Code OTP IA certifié généré : ${res.code} (Ref: ${res.confirmationCode}). Saisissez-le ci-dessous pour valider.`);
      } else {
        setCitizenError("Échec de la génération du code OTP par l'IA.");
      }
    } catch {
      setCitizenError("Une erreur est survenue lors de la communication avec le serveur d'IA.");
    } finally {
      setCitizenLoading(false);
    }
  };

  // Validation finale du code de confirmation citoyen via IA
  const handleVerifyCitizenAccess = async (e: React.FormEvent) => {
    e.preventDefault();
    setCitizenError('');

    if (!enteredOtp || enteredOtp.trim().length < 4) {
      setCitizenError("Veuillez insérer le code de confirmation IA.");
      return;
    }

    setCitizenLoading(true);
    try {
      const result = await verifyEcoCitizenAiOtp(
        citizenPhone,
        enteredOtp.trim(),
        citizenNom.trim() || 'Éco-Citoyen RDC',
        citizenCommune,
        citizenAddress.trim()
      );

      if (result.success && result.session) {
        onAuthenticated(result.session);
      } else {
        setCitizenError(result.error || 'Code OTP IA incorrect ou expiré.');
      }
    } catch {
      setCitizenError("Erreur de validation de l'Espace Éco-Citoyen.");
    } finally {
      setCitizenLoading(false);
    }
  };

  // =========================================================================
  // 2. MODALES DISCRÈTES & SÉCURISÉES POUR LES AGENTS & INSPECTEURS (2FA)
  // =========================================================================
  type AgentModalType = 'none' | 'inspecteur' | 'brigadier' | 'admin';
  const [activeAgentModal, setActiveAgentModal] = useState<AgentModalType>('none');
  const [agentSecurityAlert, setAgentSecurityAlert] = useState<{ isBlocked: boolean; message: string } | null>(null);

  // --- A. INSPECTEUR : DOUBLE AUTHENTIFICATION OBLIGATOIRE ---
  // Étape 1 : Code personnel transmis par l'administrateur principal par email
  // Étape 2 : Confirmation secondaire
  const [inspectorEmail, setInspectorEmail] = useState('');
  const [inspectorPersonalCode, setInspectorPersonalCode] = useState('');
  const [inspectorSecondaryCode, setInspectorSecondaryCode] = useState('');
  const [inspectorName, setInspectorName] = useState('');
  const [inspectorLoading, setInspectorLoading] = useState(false);

  const handleInspectorLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setAgentSecurityAlert(null);
    setInspectorLoading(true);

    const cleanEmail = inspectorEmail.trim().toLowerCase();
    const cleanPersonal = inspectorPersonalCode.trim();
    const cleanSecondary = inspectorSecondaryCode.trim();

    try {
      const res = await fetch('/api/security/inspecteur/verify-2fa', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          agentEmail: cleanEmail,
          personalCode: cleanPersonal,
          secondaryConfirmationCode: cleanSecondary,
          inspectorName: inspectorName.trim()
        })
      });

      const data = await res.json();

      if (res.ok && data.success) {
        // Double authentification inspecteur réussie
        const inspectorSession: UserAuthSession = {
          isAuthenticated: true,
          role: 'institutionnel',
          userType: 'superviseur',
          identifier: cleanEmail,
          displayName: `Insp. ${inspectorName.trim() || cleanEmail.split('@')[0]}`,
          commune: 'Cellule d\'Inspection Kinshasa',
          loginTimestamp: Date.now()
        };
        onAuthenticated(inspectorSession);
        setActiveAgentModal('none');
      } else {
        // Blocage immédiat et journalisation obligatoire dans la base centrale
        await recordSecurityAccessLog({
          identity: cleanEmail || cleanPersonal || 'Inspecteur Non Identifié',
          targetSpace: 'INSPECTEUR',
          action: 'TENTATIVE_ACCES_REFUSEE',
          status: 'BLOQUÉ',
          reason: data.error || 'Échec de double authentification Inspecteur (code personnel ou confirmation secondaire invalide).'
        });

        setAgentSecurityAlert({
          isBlocked: true,
          message: data.error || "ACCÈS BLOQUÉ : Le code agent personnel transmis par l'administrateur principal ou le code de confirmation secondaire 2FA est invalide. Tentative immédiatement journalisée dans la base centrale."
        });
      }
    } catch {
      setAgentSecurityAlert({
        isBlocked: true,
        message: "Échec de vérification du serveur d'authentification des inspecteurs."
      });
    } finally {
      setInspectorLoading(false);
    }
  };

  // --- B. BRIGADIER : DOUBLE AUTHENTIFICATION RENFORCÉE ---
  const [brigadierMatricule, setBrigadierMatricule] = useState('');
  const [brigadierReinforceCode, setBrigadierReinforceCode] = useState('');
  const [brigadierNom, setBrigadierNom] = useState('');
  const [brigadierLoading, setBrigadierLoading] = useState(false);

  const handleBrigadierLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setAgentSecurityAlert(null);
    setBrigadierLoading(true);

    const cleanMatricule = brigadierMatricule.trim();
    const cleanReinforce = brigadierReinforceCode.trim();

    try {
      const res = await fetch('/api/security/brigadier/verify-2fa', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          brigadierMatricule: cleanMatricule,
          reinforcementCode: cleanReinforce,
          brigadierName: brigadierNom.trim()
        })
      });

      const data = await res.json();

      if (res.ok && data.success) {
        const brigadeSession: UserAuthSession = {
          isAuthenticated: true,
          role: 'institutionnel',
          userType: 'brigade',
          identifier: cleanMatricule,
          displayName: `Brig. ${brigadierNom.trim() || cleanMatricule}`,
          commune: 'Brigade Kinshasa',
          loginTimestamp: Date.now()
        };
        onAuthenticated(brigadeSession);
        setActiveAgentModal('none');
      } else {
        await recordSecurityAccessLog({
          identity: cleanMatricule || 'Brigadier Non Identifié',
          targetSpace: 'BRIGADIER',
          action: 'TENTATIVE_BRIGADE_REFUSEE',
          status: 'BLOQUÉ',
          reason: data.error || 'Double authentification renforcée échouée pour la brigade.'
        });

        setAgentSecurityAlert({
          isBlocked: true,
          message: data.error || "ACCÈS BLOQUÉ : Matricule ou code d'authentification renforcée incorrect. Tentative bloquée et journalisée."
        });
      }
    } catch {
      setAgentSecurityAlert({
        isBlocked: true,
        message: "Erreur de connexion au terminal de vérification de brigade."
      });
    } finally {
      setBrigadierLoading(false);
    }
  };

  // --- C. ESPACE ADMINISTRATEURS (RÉSERVÉ STRICTEMENT À L'ADMINISTRATEUR PRINCIPAL) ---
  const [adminEmailInput, setAdminEmailInput] = useState(OFFICIAL_ADMIN_EMAIL);
  const [adminPasswordInput, setAdminPasswordInput] = useState('');
  const [adminLoading, setAdminLoading] = useState(false);

  const handleAdminLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setAgentSecurityAlert(null);
    setAdminLoading(true);

    const cleanEmail = adminEmailInput.trim().toLowerCase();
    const cleanPass = adminPasswordInput.trim();

    // Règle formelle : SEUL l'administrateur principal (environnementplusrdc@gmail.com) peut accéder
    if (cleanEmail !== OFFICIAL_ADMIN_EMAIL.toLowerCase()) {
      await recordSecurityAccessLog({
        identity: cleanEmail || 'Inconnu',
        targetSpace: 'ADMINISTRATEUR',
        action: 'TENTATIVE_INTRUSION_ADMIN_INTERDITE',
        status: 'BLOQUÉ',
        reason: `Tentative d'ouverture de l'Espace Administrateurs avec une adresse non autorisée (${cleanEmail}). Accès formellement interdit.`
      });

      setAgentSecurityAlert({
        isBlocked: true,
        message: `ACCÈS FORMELLEMENT INTERDIT : Seul l'Administrateur Principal (${OFFICIAL_ADMIN_EMAIL}) peut ouvrir cet espace. Votre identifiant a été bloqué et archivé dans le journal de sécurité.`
      });
      setAdminLoading(false);
      return;
    }

    try {
      const result = await authenticateAdministrator(cleanPass, cleanEmail);
      if (result.success && result.session) {
        onAuthenticated(result.session);
        setActiveAgentModal('none');
      } else {
        await recordSecurityAccessLog({
          identity: cleanEmail,
          targetSpace: 'ADMINISTRATEUR',
          action: 'ECHEC_MOT_DE_PASSE_ADMIN',
          status: 'BLOQUÉ',
          reason: "Mot de passe maître de l'administrateur principal incorrect."
        });

        setAgentSecurityAlert({
          isBlocked: true,
          message: result.error || "Mot de passe maître invalide. Tentative bloquée et journalisée."
        });
      }
    } catch {
      setAgentSecurityAlert({
        isBlocked: true,
        message: "Erreur de communication avec le serveur d'administration."
      });
    } finally {
      setAdminLoading(false);
    }
  };

  // AI Studio direct bypass (developer only)
  const handleAiStudioAdminLogin = async () => {
    const result = await authenticateAdministrator('environnementplus', OFFICIAL_ADMIN_EMAIL);
    if (result.success && result.session) {
      onAuthenticated(result.session);
    }
  };

  return (
    <div className="min-h-screen bg-slate-900 text-slate-100 flex flex-col justify-between font-sans selection:bg-emerald-600 selection:text-white">
      
      {/* Top Banner - République Démocratique du Congo & Ets ENVIRONNEMENT-PLUS */}
      <header className="w-full bg-slate-950/90 border-b border-slate-800 py-3 px-4 sm:px-6 backdrop-blur-md sticky top-0 z-30">
        <div className="max-w-5xl mx-auto flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 rounded-2xl bg-emerald-700 text-white flex items-center justify-center font-bold text-sm shadow-md border border-emerald-500/30">
              EW
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <h1 className="text-sm sm:text-base font-bold text-white tracking-tight">EWaste Mobile</h1>
                <span className="text-[10px] font-mono font-semibold bg-emerald-950 text-emerald-400 px-2 py-0.5 rounded border border-emerald-700/50">
                  RDC
                </span>
              </div>
              <p className="text-[11px] text-slate-400 font-medium">Ets ENVIRONNEMENT-PLUS • Assainissement & Salubrité</p>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              type="button"
              onClick={() => setShowUpdateModal(true)}
              className="text-xs bg-slate-800 hover:bg-slate-700 border border-slate-700 text-slate-300 hover:text-white px-3 py-1.5 rounded-xl transition flex items-center gap-1.5 cursor-pointer"
            >
              <RefreshCw className="w-3.5 h-3.5 text-emerald-400" />
              <span className="hidden sm:inline">Mises à jour</span>
            </button>
          </div>
        </div>
      </header>

      {/* Main Content: UN SEUL GRAND ESPACE VISIBLE POUR LA CONNEXION DES CITOYENS */}
      <main className="max-w-3xl w-full mx-auto px-4 sm:px-6 py-8 sm:py-12 flex-1 flex flex-col justify-center">
        
        {/* Titre & Message d'Accueil Citoyen */}
        <div className="text-center mb-8 space-y-2">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-emerald-950/80 border border-emerald-700/60 text-emerald-300 text-xs font-semibold mb-1 shadow-sm">
            <Users className="w-4 h-4 text-emerald-400" />
            <span>Portail d'Accès Citoyen Officiel</span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
            Espace Éco-Citoyen Kinshasa
          </h2>
          <p className="text-xs sm:text-sm text-slate-400 max-w-lg mx-auto leading-relaxed">
            Signalez les dépotoirs sauvages, payez votre taxe de salubrité communale et suivez la salubrité de votre quartier en RDC.
          </p>
        </div>

        {/* GRAND ESPACE VISIBLE : CARTE DE CONNEXION CITOYENNE */}
        <div className="bg-slate-950 border border-slate-800 rounded-3xl p-6 sm:p-10 shadow-2xl relative overflow-hidden backdrop-blur-md ring-1 ring-slate-700/40">
          
          <div className="flex items-center justify-between border-b border-slate-800 pb-5 mb-6">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-2xl bg-emerald-600/20 border border-emerald-500/40 flex items-center justify-center text-emerald-400 font-bold">
                <Users className="w-6 h-6" />
              </div>
              <div>
                <h3 className="text-base sm:text-lg font-bold text-white">
                  Connexion Simple et Sécurisée
                </h3>
                <p className="text-xs text-slate-400">
                  Accès instantané par code de confirmation automatique (sans mot de passe complexe).
                </p>
              </div>
            </div>
            <span className="hidden sm:inline-block text-[11px] bg-emerald-950 text-emerald-300 border border-emerald-800/80 font-semibold px-2.5 py-1 rounded-full">
              Ouvert à tous les citoyens
            </span>
          </div>

          {/* Message d'erreur citoyen */}
          {citizenError && (
            <div className="mb-6 p-4 bg-rose-950/60 border border-rose-800/80 rounded-2xl text-xs text-rose-200 flex items-start gap-3 animate-fade-in">
              <AlertTriangle className="w-5 h-5 text-rose-400 shrink-0 mt-0.5" />
              <div>
                <p className="font-bold">Attention</p>
                <p className="text-rose-300/90">{citizenError}</p>
              </div>
            </div>
          )}

          {/* Message de confirmation généré */}
          {citizenSuccessMsg && (
            <div className="mb-6 p-4 bg-emerald-950/60 border border-emerald-700/80 rounded-2xl text-xs text-emerald-200 flex items-start gap-3 animate-fade-in">
              <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0 mt-0.5" />
              <div>
                <p className="font-bold">Code automatique disponible</p>
                <p className="text-emerald-300">{citizenSuccessMsg}</p>
              </div>
            </div>
          )}

          {/* Formulaire Citoyen étape 1 : Saisie coordonnées + génération automatique du code */}
          {!citizenOtpSent ? (
            <form onSubmit={handleGenerateCitizenCode} className="space-y-5">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-slate-300 mb-2">
                    Votre Prénom ou Nom complet *
                  </label>
                  <input
                    type="text"
                    value={citizenNom}
                    onChange={(e) => setCitizenNom(e.target.value)}
                    placeholder="Ex: Patient Mukendi"
                    className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-sm text-white placeholder-slate-500 focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 transition"
                    required
                    autoFocus
                  />
                </div>

                <div>
                  <label className="block text-xs font-bold text-slate-300 mb-2">
                    Numéro de téléphone mobile *
                  </label>
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none text-slate-400">
                      <Smartphone className="w-4 h-4 text-emerald-400" />
                    </div>
                    <input
                      type="tel"
                      value={citizenPhone}
                      onChange={(e) => setCitizenPhone(e.target.value)}
                      placeholder="+243 81 234 5678"
                      className="w-full bg-slate-900 border border-slate-700 rounded-xl pl-10 pr-4 py-3 text-sm font-mono text-white placeholder-slate-500 focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 transition"
                      required
                    />
                  </div>
                </div>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-300 mb-2">
                  Adresse précise (Avenue, Numéro, Quartier) *
                </label>
                <input
                  type="text"
                  value={citizenAddress}
                  onChange={(e) => setCitizenAddress(e.target.value)}
                  placeholder="Ex: Av. de la Paix No. 12, Quartier résidentiel"
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-sm text-white placeholder-slate-500 focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 transition"
                  required
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-300 mb-2">
                  Commune de résidence (Kinshasa)
                </label>
                <select
                  value={citizenCommune}
                  onChange={(e) => setCitizenCommune(e.target.value)}
                  className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 text-sm text-white focus:outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 transition"
                >
                  {KINSHASA_COMMUNES.map((comm) => (
                    <option key={comm} value={comm}>
                      Commune de {comm}
                    </option>
                  ))}
                </select>
              </div>

              <div className="p-3.5 bg-slate-900/90 border border-slate-800 rounded-xl flex items-center gap-2.5 text-xs text-slate-400">
                <Info className="w-4 h-4 text-emerald-400 shrink-0" />
                <span>Connexion instantanée, gratuite et sans restriction pour tous les résidents de Kinshasa et de la RDC.</span>
              </div>

              <div className="pt-2">
                <button
                  type="submit"
                  disabled={citizenLoading}
                  className="w-full bg-emerald-600 hover:bg-emerald-500 active:bg-emerald-700 disabled:opacity-50 text-slate-950 px-6 py-3.5 rounded-xl font-bold text-sm shadow-lg shadow-emerald-950/50 transition flex items-center justify-center space-x-2 cursor-pointer"
                >
                  {citizenLoading ? (
                    <RefreshCw className="w-5 h-5 animate-spin" />
                  ) : (
                    <Sparkles className="w-5 h-5 text-slate-950" />
                  )}
                  <span>Générer mon code de confirmation et me connecter</span>
                </button>
              </div>
            </form>
          ) : (
            /* Formulaire Citoyen étape 2 : Confirmation immédiate */
            <form onSubmit={handleVerifyCitizenAccess} className="space-y-6">
              <div className="bg-emerald-950/40 border border-emerald-800/80 rounded-2xl p-4 text-center space-y-2">
                <p className="text-xs text-emerald-300 font-semibold">
                  Votre code de confirmation automatique a été généré :
                </p>
                <div className="text-3xl font-mono font-black tracking-widest text-emerald-400 bg-slate-900 py-2 px-6 rounded-xl border border-emerald-700/50 inline-block shadow-inner">
                  {autoGeneratedCode}
                </div>
                <p className="text-[11px] text-slate-400">
                  Numéro associé : <span className="font-mono text-white">{citizenPhone}</span> • Commune : <span className="text-white font-medium">{citizenCommune}</span>
                </p>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-300 mb-2 text-center">
                  Confirmez le code à 6 chiffres :
                </label>
                <input
                  type="text"
                  maxLength={6}
                  value={enteredOtp}
                  onChange={(e) => setEnteredOtp(e.target.value.replace(/\D/g, ''))}
                  placeholder="Code de confirmation"
                  className="w-full max-w-xs mx-auto block bg-slate-900 border border-emerald-600 focus:bg-slate-950 rounded-xl px-4 py-3 text-2xl font-mono text-center tracking-widest text-emerald-400 focus:outline-none focus:ring-3 focus:ring-emerald-500/20 transition"
                  required
                  autoFocus
                />
              </div>

              <div className="flex flex-col sm:flex-row items-center justify-between gap-3 pt-2">
                <button
                  type="button"
                  onClick={() => setCitizenOtpSent(false)}
                  className="text-xs text-slate-400 hover:text-slate-200 underline cursor-pointer"
                >
                  Modifier mes informations
                </button>

                <button
                  type="submit"
                  disabled={citizenLoading}
                  className="w-full sm:w-auto bg-emerald-600 hover:bg-emerald-500 active:bg-emerald-700 disabled:opacity-50 text-slate-950 px-8 py-3 rounded-xl text-sm font-bold shadow-lg transition flex items-center justify-center space-x-2 cursor-pointer"
                >
                  {citizenLoading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <CheckCircle2 className="w-4 h-4" />}
                  <span>Confirmer et Accéder à mon Espace Citoyen</span>
                </button>
              </div>
            </form>
          )}

        </div>

        {/* Garanties légales et sécurité citoyenne */}
        <div className="mt-8 flex flex-wrap items-center justify-center gap-4 sm:gap-8 text-xs text-slate-400">
          <div className="flex items-center gap-1.5">
            <Check className="w-4 h-4 text-emerald-400" />
            <span>Loi n° 11/009 du 09 juillet 2011 (Environnement RDC)</span>
          </div>
          <div className="flex items-center gap-1.5">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            <span>Données citoyennes protégées & sécurisées</span>
          </div>
          <div className="flex items-center gap-1.5">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            <span>Couverture : 24 Communes de Kinshasa</span>
          </div>
        </div>

        {/* AI Studio Only Developer Mode Bypass */}
        {isAiStudioAdmin && (
          <div className="mt-8 p-3.5 bg-slate-950 text-white rounded-2xl border border-slate-800 flex items-center justify-between text-xs">
            <div>
              <span className="font-bold text-amber-400 block">Mode Développeur AI Studio</span>
              <span className="text-slate-400">Accès rapide réservé à l'Administrateur Principal</span>
            </div>
            <button
              type="button"
              onClick={handleAiStudioAdminLogin}
              className="bg-emerald-600 hover:bg-emerald-500 text-slate-950 px-3.5 py-1.5 rounded-xl font-bold transition cursor-pointer"
            >
              Ouvrir Dashboard Admin
            </button>
          </div>
        )}

      </main>

      {/* ========================================================================= */}
      {/* 3. PIED DE PAGE AVEC BOUTONS DISCRETS RÉSERVÉS AUX AGENTS INFORMÉS */}
      {/* Non accessibles aux citoyens ordinaires, protégés par double authentification 2FA */}
      {/* ========================================================================= */}
      <footer className="w-full bg-slate-950 border-t border-slate-800/80 py-4 px-4 sm:px-6 text-xs text-slate-400">
        <div className="max-w-5xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          
          <div>
            <span className="text-slate-300 font-semibold">Ets ENVIRONNEMENT-PLUS</span> — Ville Province de Kinshasa, RDC
          </div>

          {/* Boutons réservés aux agents informés (Discrets, sécurisés, non accessibles aux citoyens) */}
          <div className="flex flex-wrap items-center justify-center gap-2">
            
            {/* Bouton 1 : Inspecteurs (Double authentification obligatoire 2FA) */}
            <button
              type="button"
              onClick={() => {
                setActiveAgentModal('inspecteur');
                setAgentSecurityAlert(null);
              }}
              className="px-2.5 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 border border-slate-800 hover:border-slate-700 text-slate-400 hover:text-slate-200 text-[11px] font-medium flex items-center gap-1.5 transition cursor-pointer"
              title="Accès réservé exclusivement aux inspecteurs avec code personnel et double authentification"
            >
              <Lock className="w-3 h-3 text-slate-500" />
              <span>Accréditation Contrôle & Inspection</span>
            </button>

            {/* Bouton 2 : Brigadiers (Double authentification renforcée) */}
            <button
              type="button"
              onClick={() => {
                setActiveAgentModal('brigadier');
                setAgentSecurityAlert(null);
              }}
              className="px-2.5 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 border border-slate-800 hover:border-slate-700 text-slate-400 hover:text-slate-200 text-[11px] font-medium flex items-center gap-1.5 transition cursor-pointer"
              title="Accès réservé exclusivement aux brigadiers opérationnels de terrain"
            >
              <Shield className="w-3 h-3 text-slate-500" />
              <span>Brigade d'Assainissement</span>
            </button>

            {/* Bouton 3 : Administrateur Principal (Strictement réservé à environnementplusrdc@gmail.com) */}
            <button
              type="button"
              onClick={() => {
                setActiveAgentModal('admin');
                setAgentSecurityAlert(null);
              }}
              className="px-2.5 py-1.5 rounded-lg bg-slate-900 hover:bg-slate-800 border border-slate-800 hover:border-slate-700 text-slate-400 hover:text-slate-200 text-[11px] font-medium flex items-center gap-1.5 transition cursor-pointer"
              title="Portail de direction générale réservé à l'administrateur principal"
            >
              <KeyRound className="w-3 h-3 text-slate-500" />
              <span>Direction Générale</span>
            </button>

          </div>

        </div>
      </footer>

      {/* ========================================================================= */}
      {/* MODALE SÉCURISÉE : ACCRÉDITATION ET DOUBLE AUTHENTIFICATION AGENTS */}
      {/* ========================================================================= */}
      {activeAgentModal !== 'none' && (
        <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="bg-slate-950 border border-slate-800 rounded-3xl max-w-lg w-full p-6 sm:p-8 shadow-2xl relative text-left">
            
            {/* Close Button */}
            <button
              onClick={() => {
                setActiveAgentModal('none');
                setAgentSecurityAlert(null);
              }}
              className="absolute top-5 right-5 text-slate-400 hover:text-white p-1 rounded-xl hover:bg-slate-800 transition cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>

            {/* Alerte de sécurité en cas de tentative non autorisée (Blocage immédiat & Traçabilité) */}
            {agentSecurityAlert && (
              <div className="mb-5 p-4 bg-rose-950/90 border border-rose-700 rounded-2xl text-xs text-rose-200 space-y-1 animate-fade-in">
                <div className="flex items-center gap-2 font-bold text-rose-300">
                  <ShieldAlert className="w-4 h-4 text-rose-400 shrink-0" />
                  <span>BLOCAGE DE SÉCURITÉ IMMÉDIAT</span>
                </div>
                <p className="text-rose-200/90 leading-relaxed">{agentSecurityAlert.message}</p>
              </div>
            )}

            {/* ------------------------------------------------------------- */}
            {/* A. FORMULAIRE INSPECTEURS (DOUBLE AUTHENTIFICATION 2FA) */}
            {/* ------------------------------------------------------------- */}
            {activeAgentModal === 'inspecteur' && (
              <div className="space-y-4">
                <div className="border-b border-slate-800 pb-4">
                  <div className="flex items-center gap-2.5 text-amber-400 font-bold text-sm">
                    <ShieldCheck className="w-5 h-5" />
                    <span>Espace Contrôle & Inspection (Double Authentification)</span>
                  </div>
                  <p className="text-xs text-slate-400 mt-1">
                    Accès réservé uniquement aux inspecteurs autorisés. Requiert le code agent personnel transmis par l'administrateur principal via votre adresse email + confirmation secondaire 2FA.
                  </p>
                </div>

                <form onSubmit={handleInspectorLogin} className="space-y-4">
                  <div>
                    <label className="block text-xs font-bold text-slate-300 mb-1">
                      Votre Nom ou Titre d'inspecteur :
                    </label>
                    <input
                      type="text"
                      value={inspectorName}
                      onChange={(e) => setInspectorName(e.target.value)}
                      placeholder="Ex: Inspecteur ACE Kinshasa"
                      className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-amber-500 transition"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-slate-300 mb-1">
                      Adresse email professionnelle de l'agent :
                    </label>
                    <input
                      type="email"
                      value={inspectorEmail}
                      onChange={(e) => setInspectorEmail(e.target.value)}
                      placeholder="inspection.ace@environnementplus.cd"
                      className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-amber-500 transition"
                      required
                    />
                  </div>

                  {/* Étape 1 : Code Agent Personnel transmis par l'administrateur */}
                  <div>
                    <div className="flex items-center justify-between mb-1">
                      <label className="block text-xs font-bold text-amber-300">
                        1. Code Agent Personnel (reçu par mail de l'Admin Principal) :
                      </label>
                      <span className="text-[10px] text-amber-400/80 font-mono">Étape 1/2</span>
                    </div>
                    <input
                      type="password"
                      value={inspectorPersonalCode}
                      onChange={(e) => setInspectorPersonalCode(e.target.value)}
                      placeholder="Code agent personnel (ex: ENV-INSPECT-2026)"
                      className="w-full bg-slate-900 border border-amber-600/60 rounded-xl px-3.5 py-2.5 text-xs font-mono text-white placeholder-slate-500 focus:outline-none focus:border-amber-400 transition"
                      required
                    />
                  </div>

                  {/* Étape 2 : Confirmation Secondaire 2FA */}
                  <div>
                    <div className="flex items-center justify-between mb-1">
                      <label className="block text-xs font-bold text-amber-300">
                        2. Code de Confirmation Secondaire 2FA :
                      </label>
                      <span className="text-[10px] text-amber-400/80 font-mono">Étape 2/2</span>
                    </div>
                    <input
                      type="password"
                      value={inspectorSecondaryCode}
                      onChange={(e) => setInspectorSecondaryCode(e.target.value)}
                      placeholder="Code de confirmation secondaire (2FA)"
                      className="w-full bg-slate-900 border border-amber-600/60 rounded-xl px-3.5 py-2.5 text-xs font-mono text-white placeholder-slate-500 focus:outline-none focus:border-amber-400 transition"
                      required
                    />
                  </div>

                  <div className="pt-2 flex justify-end gap-2">
                    <button
                      type="button"
                      onClick={() => setActiveAgentModal('none')}
                      className="px-4 py-2.5 rounded-xl text-xs font-semibold text-slate-400 hover:text-white bg-slate-900 border border-slate-800 transition cursor-pointer"
                    >
                      Fermer
                    </button>
                    <button
                      type="submit"
                      disabled={inspectorLoading}
                      className="px-6 py-2.5 rounded-xl text-xs font-bold text-slate-950 bg-amber-400 hover:bg-amber-300 transition flex items-center gap-2 cursor-pointer shadow-md"
                    >
                      {inspectorLoading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Lock className="w-4 h-4" />}
                      <span>Valider la Double Authentification</span>
                    </button>
                  </div>
                </form>
              </div>
            )}

            {/* ------------------------------------------------------------- */}
            {/* B. FORMULAIRE BRIGADIERS (DOUBLE AUTHENTIFICATION RENFORCÉE) */}
            {/* ------------------------------------------------------------- */}
            {activeAgentModal === 'brigadier' && (
              <div className="space-y-4">
                <div className="border-b border-slate-800 pb-4">
                  <div className="flex items-center gap-2.5 text-sky-400 font-bold text-sm">
                    <Trash2 className="w-5 h-5" />
                    <span>Brigade d'Assainissement Opérationnelle</span>
                  </div>
                  <p className="text-xs text-slate-400 mt-1">
                    Accès réservé exclusivement aux brigadiers de terrain autorisés. Double authentification renforcée requise.
                  </p>
                </div>

                <form onSubmit={handleBrigadierLogin} className="space-y-4">
                  <div>
                    <label className="block text-xs font-bold text-slate-300 mb-1">
                      Nom ou Chef d'équipe :
                    </label>
                    <input
                      type="text"
                      value={brigadierNom}
                      onChange={(e) => setBrigadierNom(e.target.value)}
                      placeholder="Ex: Brigadier Salubrité Kalamu"
                      className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3.5 py-2.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-sky-500 transition"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-sky-300 mb-1">
                      1. Matricule d'Intervention Brigade (Étape 1/2) :
                    </label>
                    <input
                      type="text"
                      value={brigadierMatricule}
                      onChange={(e) => setBrigadierMatricule(e.target.value)}
                      placeholder="Ex: ENV-BRIGADE-2026"
                      className="w-full bg-slate-900 border border-sky-600/60 rounded-xl px-3.5 py-2.5 text-xs font-mono text-white placeholder-slate-500 focus:outline-none focus:border-sky-400 transition"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-sky-300 mb-1">
                      2. Code de Sécurité Opérationnel Renforcé (Étape 2/2) :
                    </label>
                    <input
                      type="password"
                      value={brigadierReinforceCode}
                      onChange={(e) => setBrigadierReinforceCode(e.target.value)}
                      placeholder="Code de sécurité 2FA brigade"
                      className="w-full bg-slate-900 border border-sky-600/60 rounded-xl px-3.5 py-2.5 text-xs font-mono text-white placeholder-slate-500 focus:outline-none focus:border-sky-400 transition"
                      required
                    />
                  </div>

                  <div className="pt-2 flex justify-end gap-2">
                    <button
                      type="button"
                      onClick={() => setActiveAgentModal('none')}
                      className="px-4 py-2.5 rounded-xl text-xs font-semibold text-slate-400 hover:text-white bg-slate-900 border border-slate-800 transition cursor-pointer"
                    >
                      Fermer
                    </button>
                    <button
                      type="submit"
                      disabled={brigadierLoading}
                      className="px-6 py-2.5 rounded-xl text-xs font-bold text-slate-950 bg-sky-400 hover:bg-sky-300 transition flex items-center gap-2 cursor-pointer shadow-md"
                    >
                      {brigadierLoading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Shield className="w-4 h-4" />}
                      <span>Valider l'Accréditation Brigade</span>
                    </button>
                  </div>
                </form>
              </div>
            )}

            {/* ------------------------------------------------------------- */}
            {/* C. FORMULAIRE DIRECTION GÉNÉRALE (ADMINISTRATEUR PRINCIPAL SEUL) */}
            {/* ------------------------------------------------------------- */}
            {activeAgentModal === 'admin' && (
              <div className="space-y-4">
                <div className="border-b border-slate-800 pb-4">
                  <div className="flex items-center gap-2.5 text-rose-400 font-bold text-sm">
                    <KeyRound className="w-5 h-5" />
                    <span>Espace Administrateurs (Strictement Restreint)</span>
                  </div>
                  <p className="text-xs text-rose-300/80 mt-1">
                    Accès réservé exclusivement à l'Administrateur Principal ({OFFICIAL_ADMIN_EMAIL}). Interdiction formelle d'ouverture par tout autre utilisateur.
                  </p>
                </div>

                <form onSubmit={handleAdminLogin} className="space-y-4">
                  <div>
                    <label className="block text-xs font-bold text-slate-300 mb-1">
                      Adresse email de l'Administrateur Principal :
                    </label>
                    <input
                      type="email"
                      value={adminEmailInput}
                      onChange={(e) => setAdminEmailInput(e.target.value)}
                      placeholder={OFFICIAL_ADMIN_EMAIL}
                      className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-rose-500 transition"
                      required
                    />
                    <span className="text-[10px] text-slate-400 mt-1 block">
                      Seule l'adresse <span className="text-rose-300 font-bold">{OFFICIAL_ADMIN_EMAIL}</span> est habilitée.
                    </span>
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-slate-300 mb-1">
                      Mot de passe maître de sécurité :
                    </label>
                    <input
                      type="password"
                      value={adminPasswordInput}
                      onChange={(e) => setAdminPasswordInput(e.target.value)}
                      placeholder="Mot de passe maître"
                      className="w-full bg-slate-900 border border-slate-700 rounded-xl px-3.5 py-2.5 text-xs text-white focus:outline-none focus:border-rose-500 transition"
                      required
                    />
                  </div>

                  <div className="pt-2 flex justify-end gap-2">
                    <button
                      type="button"
                      onClick={() => setActiveAgentModal('none')}
                      className="px-4 py-2.5 rounded-xl text-xs font-semibold text-slate-400 hover:text-white bg-slate-900 border border-slate-800 transition cursor-pointer"
                    >
                      Fermer
                    </button>
                    <button
                      type="submit"
                      disabled={adminLoading}
                      className="px-6 py-2.5 rounded-xl text-xs font-bold text-white bg-rose-700 hover:bg-rose-600 transition flex items-center gap-2 cursor-pointer shadow-md"
                    >
                      {adminLoading ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Lock className="w-4 h-4" />}
                      <span>Ouvrir l'Espace Administrateurs</span>
                    </button>
                  </div>
                </form>
              </div>
            )}

          </div>
        </div>
      )}

      {/* Online Update Modal */}
      <OnlineUpdateModal
        isOpen={showUpdateModal}
        onClose={() => setShowUpdateModal(false)}
      />

    </div>
  );
}
